### ISSUE TITLE
WatchTogether: Set title and thumbnail field for new youtube videos and if possible thumbnail

### ISSUE THREAD

**Issue by tygore587** [tygore587/DiscordBroyotaBot#28]
## Body
```json
{
    "w2g_api_key": "xxx",
    "add_items": [
        {
            "url": "xxx",
            "title": "xxx",
            "thumb": "https://i.ytimg.com/vi/xvH-1F9X8L8/hqdefault.jpg"
        }
    ]
}
```

## Thumbnail generation
It has the format: 
`https://i.ytimg.com/vi/<videoId>/<quality>.jpg` If you use the webpage from watch together it uses `hqdefault` as quality parameter.

## TODOs
- [ ] Generate thumbnail url
- [ ] get youtube video name if possible
- [ ] Set values in body
