### ISSUE TITLE
Gas pricing

### ISSUE THREAD

**Issue by tygore587** [tygore587/DiscordBroyotaBot#34]
Integrate https://creativecommons.tankerkoenig.de/ into project

- [ ] Get api key
- [ ] Implement api client

## Tasks
- [ ] User can find their gas station
  - [ ] Implement api endpoint
  - [ ] Implement Bot command
    - Save multiple gas stations?

- [ ] User can get gas station pricing for saved gas station
   - [ ] Implement api endpoint
   - [ ] Implement bot command
   
- [ ] User can get pricing for their position
  - [ ] Implement endpoint with lat/long
    - maybe implement reverse search for cities, so user can just add a city?
  - [ ] Implement bot command
